name: 'WissKI base'
description: 'Basic WissKI environment with default data model.'
type: 'Site'

install:
  - file_mdm
  - file_mdm_exif
  - file_mdm_font
  - sophron
  - image_effects
  - imagemagick
  - colorbox
  - geofield
  - viewfield
  - inline_entity_form
  - wisski_pathbuilder
  - wisski_core
  - wisski_autocomplete
  - wisski_salz
  - wisski_adapter_sparql11_pb
  - wisski

config:
  import:
    image_effects: "*"
    imagemagick: "*"
    colorbox: "*"
    geofield: "*"
    viewfield: "*"
    inline_entity_form: "*"
    wisski: "*"
