name: 'WissKI base'
description: 'Basic WissKI environment with default data model.'
type: 'Site'
recipes:
  - standard
install:
  - file_mdm
  - file_mdm_exif
  - file_mdm_font
  - sophron
  - image_effects
  - imagemagick
  - geofield
  - viewfield
  - inline_entity_form
  - wisski
  - wisski_iip_image
  - wisski_mirador
config:
  import:
    image_effects: "*"
    imagemagick: "*"
    geofield: "*"
    viewfield: "*"
    inline_entity_form: "*"
    wisski: "*"
